language: go
sudo: required
services:
  - docker
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/golang/lint/golint
script:
  - make test
deploy:
  provider: script
  script: scripts/dev/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.8.3'
notifications:
  email: change
